### ISSUE TITLE
SignUp Feature

### ISSUE THREAD

**Issue by zinahalnajjar** [zinahalnajjar/Sysc4806-Project#9]

**Comment by zinahalnajjar** [comment]
will take user input:
first name 
last name 
email 
password 
and store in the application as data associated with each user, email and password will be used by the user to login into the application

**Comment by zinahalnajjar** [comment]
user will be able to log into the application using their email and password, there will be two types of users an owner and a buyer.

**Comment by ToobaKS** [comment]
Implemented
